### PR TITLE
feat(style): remove styled components

### PR DESCRIPTION
**Pull request by pbrandone**
This PR is a suggestion.

Having to use different tools for styling is not that uncommon.
For instance, recently we did a project using chakra and now we have to use CSS modules.
@danilowoz tried stitches and we might even use theme-ui in some cases.

Adding styled components (which is still my go-to tool for styling react apps) is very straightforward and arguably shouldn't even be considered tooling – making it fall outside of the scope of this project.

### CODE REVIEW

**Comment by Cleysonlb** [comment]
Why did you remove `__document.tsx` @pbrandone ?

**Comment by pbrandone** [comment]
@Cleysonlb the only reason we had a _document was to [setup SSR for styled components](https://styled-components.com/docs/advanced#server-side-rendering).

But it's as easy as copying [this file](https://github.com/vercel/next.js/blob/master/examples/with-styled-components/pages/_document.js)

**Comment by Cleysonlb** [comment]
What do you think about maintaining a default `_document` like [this](https://nextjs.org/docs/advanced-features/custom-document)? It is important to have a `_document` page

**Comment by pbrandone** [comment]
@Cleysonlb I think not having a document it's the same as having that one (which is the default)

**Review by Cleysonlb — APPROVED** [review]

**Review by pedrobslisboa — APPROVED** [review]

**Pull request merged**
